# Generated by Django 4.0.4 on 2022-04-22 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistritoFederal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distrito_federal', models.PositiveIntegerField()),
                ('cabecera', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Distrito Federal',
                'verbose_name_plural': 'Distritos Federales',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('entidad', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('localidad', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_municipio', to='app.entidad')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='PaperSize',
            fields=[
                ('tipo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=3, verbose_name='Tamaño')),
                ('descripcion', models.CharField(max_length=25, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tamaño',
                'verbose_name_plural': 'Tamaños de Papel',
            },
        ),
        migrations.CreateModel(
            name='StatusPusinex',
            fields=[
                ('status', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados de PUSINEX',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seccion', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('U', 'Urbana'), ('R', 'Rural'), ('M', 'Mixta')], max_length=1)),
                ('distrito_federal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distrito_federal_seccion', to='app.distritofederal')),
                ('entidad', models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, related_name='entidad_seccion', to='app.entidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_seccion', to='app.municipio')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='Pusinex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_levantamiento', models.DateField()),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pusinex_localidad', to='app.localidad')),
                ('status_pusinex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pusinex_status', to='app.statuspusinex')),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_seccion', to='app.seccion'),
        ),
        migrations.CreateModel(
            name='DistritoLocal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distrito_local', models.PositiveIntegerField()),
                ('cabecera', models.CharField(max_length=100)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_distrito_local', to='app.entidad')),
            ],
            options={
                'verbose_name': 'Distrito Local',
                'verbose_name_plural': 'Distritos Locales',
            },
        ),
        migrations.AddField(
            model_name='distritofederal',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_distrito', to='app.entidad'),
        ),
        migrations.AddConstraint(
            model_name='localidad',
            constraint=models.UniqueConstraint(fields=('seccion', 'localidad'), name='idxLocalidad'),
        ),
    ]
