# Generated by Django 4.0.3 on 2022-04-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistritoFederal',
            fields=[
                ('distrito_federal', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cabecera', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Distrito Federal',
                'verbose_name_plural': 'Distritos Federales',
            },
        ),
        migrations.CreateModel(
            name='DistritoLocal',
            fields=[
                ('distrito_local', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cabecera', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Distrito Federal',
                'verbose_name_plural': 'Distritos Federales',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('entidad', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('municipio', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cabecera', models.CharField(max_length=100)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_municipio', to='app.entidad')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('seccion', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('U', 'Urbana'), ('R', 'Rural'), ('M', 'Mixta')], max_length=1)),
                ('distrito_federal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distrito_federal_seccion', to='app.distritofederal')),
                ('distrito_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distrito_local_seccion', to='app.distritolocal')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_seccion', to='app.entidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_seccion', to='app.municipio')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.AddField(
            model_name='distritolocal',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_distrito_local', to='app.entidad'),
        ),
        migrations.AddField(
            model_name='distritofederal',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_distrito', to='app.entidad'),
        ),
    ]
