# Generated by Django 4.0.4 on 2022-04-27 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=150)),
                ('clave', models.TextField(max_length=4)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.distritofederal')),
            ],
            options={
                'verbose_name': 'Técnico Cartógrafo',
                'verbose_name_plural': 'Técnicos',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveSmallIntegerField()),
                ('hoja', models.PositiveSmallIntegerField()),
                ('fecha_act', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='')),
                ('pusinex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pusinex')),
                ('tac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tac')),
            ],
        ),
    ]
