# Generated by Django 4.0.3 on 2022-04-07 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_distritolocal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccion',
            name='distrito_local',
        ),
        migrations.AlterField(
            model_name='seccion',
            name='entidad',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, related_name='entidad_seccion', to='app.entidad'),
        ),
    ]
