# Generated by Django 4.0.3 on 2022-04-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_seccion_distrito_local_alter_seccion_entidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PapperSize',
            fields=[
                ('tipo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=3, verbose_name='Tamaño')),
                ('descripcion', models.CharField(max_length=25, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tamaño',
                'verbose_name_plural': 'Tamaños de Papel',
            },
        ),
        migrations.CreateModel(
            name='StatusPusinex',
            fields=[
                ('status', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados de PUSINEX',
            },
        ),
    ]
